"""Add token_hash to authentication_tokens

Revision ID: 3eb1edd433bc
Revises: d47f25d86972
Create Date: 2026-06-28 23:03:40.408547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb1edd433bc'
down_revision: Union[str, None] = 'd47f25d86972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM authentication_tokens')
    op.add_column('authentication_tokens', sa.Column('token_hash', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'authentication_tokens', ['token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authentication_tokens', type_='unique')
    op.drop_column('authentication_tokens', 'token_hash')
    # ### end Alembic commands ###
