"""Add cover_image_url to projects

Revision ID: b7cb951ad1a3
Revises: b6fac2d78d1f
Create Date: 2026-06-28 17:14:40.358948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7cb951ad1a3'
down_revision: Union[str, None] = 'b6fac2d78d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('cover_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'cover_image_url')
    # ### end Alembic commands ###
