"""Add production_date to batches

Revision ID: d47f25d86972
Revises: 60ddbd7951e7
Create Date: 2026-06-28 22:49:51.547227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47f25d86972'
down_revision: Union[str, None] = '60ddbd7951e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('production_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'production_date')
    # ### end Alembic commands ###
