"""add encryption_key to organization

Revision ID: eb6df3b6cb94
Revises: b7cb951ad1a3
Create Date: 2026-06-28 18:31:44.750936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6df3b6cb94'
down_revision: Union[str, None] = 'b7cb951ad1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('encryption_key', sa.String(), nullable=True))
    op.execute("UPDATE organizations SET encryption_key = md5(random()::text)")
    op.alter_column('organizations', 'encryption_key', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'encryption_key')
    # ### end Alembic commands ###
